name: si2_p1_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
